server {
    listen 80;
    root /var/www/html;
    index index.php index.html;
    client_max_body_size 50M;
 
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
 
    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout 60;
    }
 
    location ~* \.(jpg|jpeg|png|gif|ico|css|js)$ {
        expires 10m;
        add_header Cache-Control "public";
    }
}
